
name: Deployment LP to EC2 DEV

on:
  push:
    branches: development
jobs:

  Deployment:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.sim_2025_LP_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.sim_2025_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.sim_2025_HOSTNAME }} '
            cd /var/www/html/sim-2025-lp &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development'
 

            

      
  
